### ISSUE TITLE
tracer init fail

### ISSUE THREAD

**Issue by ray1888** [jaegertracing/jaeger-client-python#103]
i was trying to combine pyspider webui (https://github.com/binux/pyspider) and jaeger-client-python together. but when i try to init a tracer in it. it just can't start pyspider webui and i traceback the reason , find out it's the ThreadLoop start() to start the thread ioloop fail and get stuck. may u help to findout why? i have searched the SO , but can't find any answer on it

**Comment by yurishkuro** [comment]
If you already have an application that uses tornado, you may initialize the tracer with an IOLoop from the main app.

**Comment by yurishkuro** [comment]
if that doesn't work, best if you could provide an example to reproduce the issue.

**Comment by ray1888** [comment]
u mean i need to use the main app tornado ioloop instead of creating a new loop for the Client ?

**Comment by yurishkuro** [comment]
I'm saying if creating a new one doesn't work you can use the main IOLoop, there's not a lot of difference.

**Comment by ray1888** [comment]
problem found . it the code problem rather than jaeger_client Problem. thank for answering problem
