### ISSUE TITLE
Understanding one_span_per_rpc configuration

### ISSUE THREAD

**Issue by kujenga** [jaegertracing/jaeger-client-python#104]
I just spent a while looking into problems with traces being improperly nested when dealing with calls between Go and Python services. It turned out that the needed fix was to set what appears to be an undocumented `one_span_per_rpc` option to false on my tracer, allowing a new span identifier to be created so that is is a proper child of the request calling my HTTP endpoint. This is the relevant code: https://github.com/jaegertracing/jaeger-client-python/blob/bbb07d46c03f0e4c369dbca93fda6011b3b39fae/jaeger_client/tracer.py#L147-L153

I see the documentation about supporting zipkin-style behavior, but am unclear on why that is the default. I'm using the jaeger, not zipkin, which I would expect is the primary use case for this library?

Is this something that it would make sense to better document and expose through the `Config` object?

**Comment by yurishkuro** [comment]
You are right, we should change the default to False.

**Comment by yurishkuro** [comment]
It's a legacy setting.

**Comment by kujenga** [comment]
Ah, great! Thanks so much for the prompt response.
