### ISSUE TITLE
Zipkin HTTP headers support

### ISSUE THREAD

**Issue by gravelg** [jaegertracing/jaeger-client-python#106]
Hello,

I'm currently working on adding Zipkin HTTP headers support to this library and would like to discuss what the preferred method for enabling support for those headers should be.

My current solution is to have a new config parameter, something like `use_zipkin_http_headers: True`, which would send the Zipkin codec as `extra_codecs` to the Tracer and take over handling of HTTP headers over the default TextCodec. 

Is this the recommended way of adding codecs to the tracer? If not, how should I be enabling the Zipkin support?

**Comment by yurishkuro** [comment]
Perhaps like this https://github.com/jaegertracing/jaeger-client-java/pull/296
