### ISSUE TITLE
Trace a AMQP Workflow

### ISSUE THREAD

**Issue by cheveyo20** [jaegertracing/jaeger-client-python#122]
Hi All,

i have a distributed processing (called Workflow1 in this case) with amqp support:

Start -- amqp--> General Processing --amqp-->Fork into two queues Task A and B

So i can trace this with jaeger :) My first attempt using inject and extract:

```
#Start
span = tracer.start_span('Workflow')
carrier = {}
tracer.inject(span, Format.TEXT_MAP ,carrier)
with tracer.start_span('ProcessInstance_Start', child_of=span) as cspan:
    time.sleep(2) # placeholder: Do some initial processing
#Then send it to the General Processing via amqp
#Sending this with the amqp msg: carrier["uber-trace-id"]
span.finish() # I think the problem lies here!
```

```
#General Processing
#recieving msg via amqp
carrier = {}
carrier['uber-trace-id'] = json_data[0]['variables']['Trace']['value']
parentspan = tracer.extract(Format.TEXT_MAP, carrier)
with tracer.start_span('GeneralProcessing', child_of=parentspan) as span:
    time.sleep(1) # placeholder: do some general processing

#send to the next topic queue: carrier['uber-trace-id'] etc.
```

So 4 issues / questions:

1) I get sometimes in the UI the result for a trace (not always):
<cannot-find-trace-name>

2) There are gaps between the spans (queue waiting time) can i fill thes gaps somehow?

3) Points to 2: I think the thing is that a span needs to be finished where it was started. But here is the Problem in general how can i handle the overall span 'Workflow' i have to finish it in the first service which is actually wrong

4) Dependency analysis via spark: it should display a dependency like the workflow instead it creates a 'star'like dependency!

I hope you can help me in anyway, pseudo code is also ok

Thanks in advance

**Comment by yurishkuro** [comment]
Q: is the program that starts the "Workflow" span long running, or does it exit quickly? If the latter, it's possible that the tracer doesn't have time to flush the spans.

2 - why do you need to fill the gaps? The messaging use case is naturally async, it's not unusual that you will have gaps in the timeline. The distance between the spans should reflect the queue wait. The only way to fill the gaps would be to instrument the queue broker so that it emits an additional span from receiving the msg to handing it out to the consumer.

3 - indeed, I recently ran into a similar scenario with long running workflows. Unless you have some sort of higher-level operation that keeps an open span for all that time, there's no way today to model the full workflow as a span. It could be done in systems based on X-Trace event model (like Facebook's Canopy). In Jaeger it would require an ability to submit in-progress spans to the backend (see https://github.com/jaegertracing/jaeger/issues/677)

4 - can you post a screenshot?

**Comment by cheveyo20** [comment]
4) Similar to this:
![image](https://user-images.githubusercontent.com/30328572/36034732-4e00c3a0-0db5-11e8-9038-d8a887b12e47.png)

But i do expect something like this:
Start -- --> General Processing ---->Fork into two queues Task A and B
I understand that this does make sense from a technical point of view, because i make everything dependeable on the overal process, how can i improve this here?

1) i put a time.sleep at the end and i think it seems to befixed so the error was caused by fast exit

3) Is this planned to be integrated? 

Is jaeger the right soloution to solve my issue or do you know something more matching to my use case :)?

Thanks

**Comment by yurishkuro** [comment]
the shape of the graph depends on how you are starting the spans. In this case it appears that Task A span is started as a child of the root span, not of "General Processing" span. If your processing `Start -- --> General Processing ---->Fork` has some form of queued messages between steps, then each message needs to carry the span context of the currently active span. That does not seem to be the case in your instrumentation.

**Comment by cheveyo20** [comment]
Thanks i worked it out :)
Last question to this topic, is it possible if i do have a following service which joins Task A & B, to show its dependency to Task A & B?
Because in the "Join Service", i am having two different span contexts

**Comment by yurishkuro** [comment]
You can certainly capture this relationship by passing two follows-from references when creating the join span. It won't have special display in the UI though - suggestions are welcome how to display it.

**Comment by Mulkave** [comment]
@cheveyo20 can you please share some details on how you got it to work? New to tracing with AMQP 😄

**Comment by mohit-chawla** [comment]
@cheveyo20 Can you share details of how you got it to work? 

@yurishkuro , is there a tracer for AMQP (rabbitmq) in python? I could not find any.  (I am trying to set up jaeger with istio, unfortunately istio-proxy(envoy) does not support protocols other than HTTP, so i am trying to manually set up instrumentation for microservices using AMQP.)

**Comment by yurishkuro** [comment]
@mohit-chawla I don't know, haven't used rabbitmq/amqp. Sounds like a reasonable case for OpenTracing instrumentation. Have you checked https://opentracing.io/registry?

**Comment by mohit-chawla** [comment]
@yurishkuro, Thanks for your prompt reply.  Yes, i checked out https://opentracing.io/registry and many other sources, there seems to be one for go (https://github.com/opentracing-contrib/go-amqp) but surprisingly nothing for python.

**Comment by yurishkuro** [comment]
then you may need to write one :-) . Having Go as a prototype should be helpful

**Comment by mohit-chawla** [comment]
Yes, i think i may end up writing one. Yes, go as prototype is useful.

**Comment by yurishkuro** [comment]
I'll close this since it does not really pertain to jaeger-client-python

@cheveyo20 if you could share the instrumentation, it might be useful to others.

**Comment by mohit-chawla** [comment]
@yurishkuro, I am trying to report spans manually from AMQP related services. Can you pl point me to a resource on how can i report a span to jaeger backend manually over http? 
My services are in kubernetes-istio env and i cant figure out how exactly istio reports spans to jaeger-collector.

**Comment by yurishkuro** [comment]
Python client doesn't support reporting spans over http right now.

**Comment by mohit-chawla** [comment]
@yurishkuro , is there any protocol over which i can send traces to jaeger collector manually in python. If yes, how?

**Comment by yurishkuro** [comment]
Not in Python, I think it's the only Jaeger client that does not support reporting over HTTP.

You can try to implement your own reporter, but our long term plan is to support HTTP in Jaeger directly, it's just nobody has time to implement it. At Uber we always report spans to the agent that runs on the host, I don't know if you can use that w/ AMQP.
