### ISSUE TITLE
We dropped dependency on `future` but still have references to `past`

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-python#133]
@sc68cal [said](https://github.com/jaegertracing/jaeger-client-python/pull/130#discussion_r171393944):

You dropped the future package from the requirements but are still referencing it.

I get a stacktrace when trying to run this in a Python 3 environment.

```
File "/usr/src/app/src/jaeger-client/jaeger_client/tracer.py", line 30, in <module>
    from .codecs import TextCodec, ZipkinCodec, ZipkinSpanFormat, BinaryCodec
  File "/usr/src/app/src/jaeger-client/jaeger_client/codecs.py", line 18, in <module>
    from past.builtins import basestring
ModuleNotFoundError: No module named 'past'
```

**Comment by debosmit** [comment]
@yurishkuro should we think about moving the py3 stuff to a separate branch till it attains stability?

**Comment by yurishkuro** [comment]
I don't want to create & maintain forks. Officially we do not support py3, but we've been making incremental changes to remove incompatibilities. As of now the only remaining issue, as far as I remember, is the unicode tests that behave differently in py2/py3.

There's a PR #114 to do CI with py3.
