### ISSUE TITLE
Config 'enabled' option should be deprecated, since it does nothing

### ISSUE THREAD

**Issue by nziebart** [jaegertracing/jaeger-client-python#145]
The tracer config has an `enabled` key, but setting the value to `False` does not do anything. The tracer will still start a reporter thread and attempt to send traces over UDP.

I guess this is not really distinguishable from it being disabled in most cases, but I would expect the tracer to default to a no-op implementation if I disable it. e.g., just leave `opentracing.tracer` as-is, since it's already a np-op impl

**Comment by yurishkuro** [comment]
`enabled` field is deprecated (we should mark it so).

But I disagree that returning a noop tracer should be part of Jaeger implementation. It can be done externally by the application using the library.

**Comment by nziebart** [comment]
Ok makes sense, that is what I'm doing anyway. Was just confusing to see the field there.

I'll change the issue title
