### ISSUE TITLE
Better support for multiple tracers/services

### ISSUE THREAD

**Issue by nziebart** [jaegertracing/jaeger-client-python#149]
In some cases it is useful to simulate the existence of different services from within the same process, e.g. when making queries to services that are not instrumented (e.g. databases). In this case we'd want the `service` on the span to be the remote service.

However, the only way to do this is to create multiple tracers. I came across this proposal https://github.com/opentracing/specification/issues/77 for adding a `service` tag, but it has not been fleshed out.

The go client makes it pretty straightforward to create multiple tracers, by having methods on the `config` object to create a `Sampler` and a `Reporter`. However the python client does all the heavy lifting inside the `initialize_tracer` method, which can only be called once.

Should we break out factory methods here like we do in the go client? (see https://github.com/jaegertracing/jaeger-client-go/blob/master/config/config.go#L269).

**Comment by yurishkuro** [comment]
> However the python client does all the heavy lifting inside the initialize_tracer method, which can only be called once.

do you actually need any heavy lifting?  Multiple tracers per process is still very much an edge case, I think it's reasonable to expect the application to do a bit of work to create them. I don't think it requires any new factory methods because the configuration class is merely a helper, it uses public constructors for the rest of the objects.

**Comment by nziebart** [comment]
You're right, it is not strictly necessary. However in practice people will probably just copy the code from the config class if they want to do this, because there are certain bits of logic that are not really trivial - e.g. wrapping the reporter with a `CompositeReporter` and `LoggingReporter` if logging is enabled. It is a strange (and brittle) pattern to inspect the config in your own code and apply this logic - it feels better done by the library.

A simple proposal would be to just add methods on the `Config` class to create a `Reporter` and `Sampler`.

You mention that this is very much an edge case - is it common for users to have things like redis, kafka, mysql instrumented? It seems like users tend to wrap the client only and not the service (e.g. in https://github.com/opentracing-contrib/python-redis)

**Comment by yurishkuro** [comment]
Fair enough. What specific methods would you like to propose? It looks like all you really need is `initialize_tracer`, maybe with an option to skip installing the global tracer.

An even better approach would be to actually implement support for setting service name via tag (per https://github.com/opentracing/specification/issues/77) and allow submitting spans for different services from the same tracer.

**Comment by dmazin** [comment]
@nziebart Hi! This issue is from 4 years ago, but I just wanted to thank you for 1) identifying a common issue 2) actually following up with a PR. And thank you, maintainers, for being receptive and for merging the PR :-D
