### ISSUE TITLE
Jaeger agent dropping spans bigger than 1500 MTU

### ISSUE THREAD

**Issue by silent-vim** [jaegertracing/jaeger-client-python#152]
Hi, thank you for opensourcing this tool along with the client libraries it is really useful. I wanted to see if there are any suggestions for the issue we are facing. 

We have multiple applications running in a docker swarm cluster. I started a Jaeger all in one docker image as well as a service reachable by its name on the port 5775 to send the spans over UDP. 

From our applications we are able to send and receive the spans which are smaller in size than the set MTU of 1500. If any of the traces are bigger than that limit we do not see the spans in Jaeger and tcp dump shows a message stating bad length > 1472

Is there any workaround this setting as accessing the agent through localhost in the docker container running the application is not possible without baking in the jaeger agent with a collector address in the Dockerfile of each application.

**Comment by yurishkuro** [comment]
The UDP protocol between clients and the agent is meant for cases where the agent is running as a daemon on the host or as a sidecar. It is not recommended if the clients talk to the agent over network. Our go and Java clients implement http transports for your scenario, but I assume you're using Python and the Python client doesn't implement such transport. It's not difficult to add if you're interesting in contributing a PR.
