### ISSUE TITLE
jaeger-client cannot be installed on older versions of setuptools

### ISSUE THREAD

**Issue by nziebart** [jaegertracing/jaeger-client-python#153]
Essentially, this is the issue: https://stackoverflow.com/questions/48048745/setup-py-require-a-recent-version-of-setuptools-before-trying-to-install

We use a `python_version` specifier in the requirements here: https://github.com/jaegertracing/jaeger-client-python/blob/3.8.0/setup.py#L38, and only recent versions of `setuptools` support this. If you try to install and your `setuptools` is older, it will fail.

Not sure what the best solution is here

**Comment by yurishkuro** [comment]
@nziebart 
```
pip install -U 'pip>=9.0'
pip install 'setuptools>=20.8.1'
```
