### ISSUE TITLE
Stacktrace is not set properly on errors

### ISSUE THREAD

**Issue by nziebart** [jaegertracing/jaeger-client-python#163]
The default opentracing impl logs the stacktrace in the event of an exception:
https://github.com/opentracing/opentracing-python/blob/master/opentracing/span.py#L199

However the stacktrace object gets converted to a string via `str(tb)` and it results in the following display in the UI: `python.exception.tb | "<traceback object at 0x7f7a2aad9638>"`

I think it might actually be easiest to fix this in opentracing, by logging a string representation of the stacktrace rather than the object

**Comment by yurishkuro** [comment]
I think the right place to fix it is in the reporter/converter. Pushing the conversion upstream to opentracing means the work will have to be done every time, even though the trace may be unsampled.

**Comment by SEJeff** [comment]
`traceback.format_exc()` is the magic to get the last raised exception as a string. The code in opentracing-python (that returns `repr(exception_object)` seems useless otherwise, but I'd expect the value to be truncated past a certain number of chars.

**Comment by nziebart** [comment]
Yeah, I think the main question here is where should we call `traceback.format_exc()`. Currently there is no real concept of a value converter, it just goes to [this function](https://github.com/jaegertracing/jaeger-client-python/blob/90ddf76da60b8a3304ea30a5ff08e188eb2f2de6/jaeger_client/thrift.py#L39) which does `str(val)`

The easy fix would be to make this conversion logic know about traceback objects and special case them. Alternatively we could let the caller pass in a callable/lambda that returns the string, which we call only if the trace is sampled.
