### ISSUE TITLE
Ability to specify custom `jaeger.hostname` useful for running in kubernetes or containers

### ISSUE THREAD

**Issue by SEJeff** [jaegertracing/jaeger-client-python#166]
This code:
https://github.com/jaegertracing/jaeger-client-python/blob/34364d06e7516384a51551f80478519a51fd13a3/jaeger_client/tracer.py#L89-L90

Is not ideal when running `jaeger_client` in containerized applications. It seems most useful to allow setting a custom hostname in the config or via an environment variable. We're currently using an `init_tracer()` like this for flask applications:

```python
def initialize_tracer():
    config = Config(
        config={
            'sampler': {
                'type': 'const',
                'param': 1,
            },
            'local_agent': {
                'reporting_host': os.environ.get('NODE_NAME', '127.0.0.1'),
            },
            'logging': True,
        },
        service_name=os.environ.get('APP_DEPLOYMENT_NAME', __name__),
    )
    return config.initialize_tracer()
```

The `NODE_NAME` env var is set via the [kubernetes downward api](https://github.com/kubernetes/website/blob/master/docs/tasks/inject-data-application/dapi-envars-pod.yaml#L17-L21) to the actual kubelet running the pod (since it runs a jaeger-agent pod on every node).

Changing the code for this seems pretty trivial, but what do you suggest we name the config and env variable for this?

**Comment by yurishkuro** [comment]
I'd suggest we do the same thing as here https://github.com/jaegertracing/jaeger-client-java/pull/371
