### ISSUE TITLE
Remote sampler always fails to refresh

### ISSUE THREAD

**Issue by nziebart** [jaegertracing/jaeger-client-python#171]
## Requirement - what kind of business use case are you trying to solve?

The remote sampler fails to refresh and always uses the default sampler

## Problem - what in Jaeger blocks you from solving the requirement?

It looks like there are two sampling endpoints on `jaeger-agent`:
`/sampling` and `/`. 
The former returns the strategy as a string (e.g. `{"strategyType":"PROBABILISTIC"}`), whereas the latter returns it as an integer (e.g. `{"strategyType":0}`)

The python client appears to be expecting the integer version, but it is querying the `/sampling` endpoint. This causes the following error when refreshing the sampling strategy:
```
  File ".../jaeger_client/sampler.py", line 438, in _update_sampler
    self._update_rate_limiting_or_probabilistic_sampler(response)
  File ".../jaeger_client/sampler.py", line 470, in _update_rate_limiting_or_probabilistic_sampler
    raise ValueError('Unsupported sampling strategy type: %s' % s_type)
ValueError: Unsupported sampling strategy type: PROBABILISTIC

```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

We should use string constants for comparison here: https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/sampler.py#L452

**Comment by black-adder** [comment]
Thanks for reporting, may I ask which version of jaeger-client and jaeger you are using?

**Comment by black-adder** [comment]
Actually, nvm, i'll take a look. It's surprising we haven't had anyone internally report this issue yet. I swear I had a test for this...

**Comment by nziebart** [comment]
It doesn't cause any runtime failures, so if the default rate of `0.001` is reasonable it might go unnoticed. Though there is a metric in the python client that counts the number of failed refreshes.
