### ISSUE TITLE
Is this is an error? (Log statement)

### ISSUE THREAD

**Issue by IMG-PRCSNG** [jaegertracing/jaeger-client-python#174]
https://github.com/jaegertracing/jaeger-client-python/blob/dee05477d551c326ee5b845fbef96606b9efe4cb/jaeger_client/reporter.py#L178

Is this supposed to read 'Span publisher exits' instead?

**Comment by black-adder** [comment]
Yup, do you mind putting up a PR for a fix? :) Maybe `Span publisher exited`
