### ISSUE TITLE
Jaeger client can't parse remote sampling strategy with Python 3.5

### ISSUE THREAD

**Issue by nielspardon** [jaegertracing/jaeger-client-python#180]
## Requirement - what kind of business use case are you trying to solve?

Run Jaeger Python Client with Python 3.5

## Problem - what in Jaeger blocks you from solving the requirement?

Python 3.5 complains about not being able to load JSON with sampling strategy from agent since it's not str but bytes.

```
Fail to parse sampling strategy from jaeger-agent: the JSON object must be str, not 'bytes' [b'{"strategyType":"PROBABILISTIC","probabilisticSampling":{"samplingRate":1}}']
```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

In sampler.py decode `response.body` to str:
```diff
-            sampling_strategies_response = json.loads(response.body)
+            sampling_strategies_response = json.loads(response.body.decode('utf-8'))
```
https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/sampler.py#L417

## Any open questions to address

None

**Comment by nielspardon** [comment]
Python 3.6 seems to have a different behavior than 3.5:
https://github.com/python/cpython/blob/3.5/Lib/json/__init__.py#L271
https://github.com/python/cpython/blob/3.6/Lib/json/__init__.py#L302

`json.loads()` accepts only `str` in 3.5 while it does accept `str`, `bytes` or `bytearray` in 3.6

In your unit tests you seem to be only testing with a `str` mock and not with a `bytes` mock which is what seems to be returned in `future.result()` in Python 3.5 (and potentially also in 3.6).
https://github.com/jaegertracing/jaeger-client-python/blob/master/tests/test_sampler.py#L356

**Comment by black-adder** [comment]
@nielspardon would you be willing to create a PR with the fix?

**Comment by nielspardon** [comment]
I opened PR #181 with a fix (including modified unit test).
