### ISSUE TITLE
Please respect semver between releases

### ISSUE THREAD

**Issue by abhinav** [jaegertracing/jaeger-client-python#185]
It looks like 2acc83e (#111) made a couple breaking changes:

- Multiple attributes were deleted from the Span class. The general
  understanding with Python libraries is that if it doesn't start with `_` it
  should be considered "public".
- Representation of Tag objects was changed.

This change was released 20 days ago as a minor release, 3.10.0. These changes
were not mentioned at all in the [CHANGELOG for that release][1] so no
migration instructions could be included either.

This was caught by a test failure on our end (fixed by uber/tchannel-python#481).

  [1]: https://github.com/jaegertracing/jaeger-client-python/blob/3.10.0/CHANGELOG.rst#3100-2018-05-09

CC @blampe @akshayjshah @prashantv

**Comment by yurishkuro** [comment]
```python
     __slots__ = ['_tracer', '_context',
                 'operation_name', 'start_time', 'end_time',
                 'logs', 'tags', 'update_lock']
```
we should change all of these to start with `_`. They are not public API, the only public API of the span is `opentracing.Span`.
