### ISSUE TITLE
Tornado ioloop overhead

### ISSUE THREAD

**Issue by nziebart** [jaegertracing/jaeger-client-python#187]
## Requirement - what kind of business use case are you trying to solve?

We want the impact of tracing on request latency to be minimal

## Problem - what in Jaeger blocks you from solving the requirement?

It appears that traces add a minimum of 0.1-0.2ms of overhead per span (more if tags are added). This is surprisingly high. If a request contains 1000 spans, then at minimum we are adding 100-200ms of latency. 

I tested this by creating a method that just makes 10,000 spans in a loop. This function takes about 1.7 seconds to execute. cProfile shows that most of the time is spent waking up the other thread in tornado (`{method 'write' of 'file' objects}` is this line https://github.com/tornadoweb/tornado/blob/master/tornado/platform/posix.py#L54):
```
In [10]: cProfile.run("time(make_spans)")
3.1972849369
         930006 function calls in 3.197 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.009    0.009    3.197    3.197 <ipython-input-3-8038e29a00aa>:1(time)
    10000    0.002    0.000    0.002    0.000 <ipython-input-5-b22977d8b0a5>:1(do_stuff)
        1    0.000    0.000    3.197    3.197 <string>:1(<module>)
    20000    0.010    0.000    0.015    0.000 context.py:17(set_active_span)
    30000    0.015    0.000    0.023    0.000 context.py:21(get_active_span)
    10000    0.030    0.000    3.188    0.000 decorators.py:22(traced_function)
    10000    0.007    0.000    0.019    0.000 ioloop.py:193(current)
    10000    0.038    0.000    2.275    0.000 ioloop.py:933(add_callback)
    30000    0.004    0.000    0.004    0.000 metrics.py:24(_noop)
    10000    0.012    0.000    2.198    0.000 posix.py:53(wake)
    10000    0.023    0.000    2.316    0.000 reporter.py:132(report_span)
    10000    0.004    0.000    0.004    0.000 sampler.py:95(is_sampled)
    20000    0.010    0.000    0.016    0.000 six.py:598(iteritems)
    50000    0.054    0.000    0.064    0.000 span.py:128(is_sampled)
    10000    0.011    0.000    0.041    0.000 span.py:13(new_active_span)
    10000    0.004    0.000    0.004    0.000 span.py:19(__init__)
    10000    0.001    0.000    0.001    0.000 span.py:192(__enter__)
    10000    0.007    0.000    2.375    0.000 span.py:199(__exit__)
    10000    0.010    0.000    0.025    0.000 span.py:23(_activate)
    10000    0.107    0.000    0.440    0.000 span.py:34(__init__)
    10000    0.007    0.000    0.008    0.000 span.py:45(__enter__)
    10000    0.012    0.000    2.415    0.000 span.py:49(__exit__)
    10000    0.012    0.000    0.028    0.000 span.py:57(restore_previous_span)
    10000    0.021    0.000    2.368    0.000 span.py:59(finish)
    10000    0.003    0.000    0.003    0.000 span.py:73(__init__)
    20000    0.134    0.000    0.315    0.000 span.py:75(set_tag)
    60000    0.011    0.000    0.011    0.000 span.py:77(context)
    30000    0.005    0.000    0.005    0.000 span.py:88(tracer)
    10000    0.015    0.000    0.015    0.000 span_context.py:25(__init__)
    10000    0.027    0.000    0.036    0.000 stack_context.py:255(wrap)
    40000    0.038    0.000    0.061    0.000 thrift.py:52(_to_string)
    20000    0.050    0.000    0.138    0.000 thrift.py:63(make_string_tag)
    10000    0.074    0.000    0.613    0.000 tracer.py:100(start_span)
    10000    0.012    0.000    0.023    0.000 tracer.py:107(instance)
    10000    0.008    0.000    0.010    0.000 tracer.py:131(_initialize_if_needed)
    10000    0.023    0.000    0.046    0.000 tracer.py:207(_emit_span_metrics)
    10000    0.017    0.000    2.335    0.000 tracer.py:225(report_span)
    10000    0.010    0.000    0.021    0.000 tracer.py:229(random_id)
    10000    0.007    0.000    0.030    0.000 tracer.py:43(for_service)
    10000    0.009    0.000    0.733    0.000 tracer.py:47(start_app_span)
    10000    0.010    0.000    0.694    0.000 tracer.py:55(start_span)
    10000    0.019    0.000    0.678    0.000 tracer.py:83(_start_span)
    10000    0.004    0.000    0.004    0.000 tracer.py:91(_maybe_include_traceback)
    20000    0.025    0.000    0.025    0.000 ttypes.py:81(__init__)
        1    0.000    0.000    0.000    0.000 vt100_input.py:278(_input_parser_generator)
    40000    0.019    0.000    0.019    0.000 {getattr}
    10000    0.009    0.000    0.009    0.000 {hasattr}
    50000    0.015    0.000    0.015    0.000 {isinstance}
    30000    0.004    0.000    0.004    0.000 {len}
    10000    0.001    0.000    0.001    0.000 {method 'append' of 'collections.deque' objects}
    20000    0.004    0.000    0.004    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
    10000    0.013    0.000    0.013    0.000 {method 'encode' of 'unicode' objects}
    10000    0.002    0.000    0.002    0.000 {method 'get' of 'dict' objects}
    10000    0.011    0.000    0.011    0.000 {method 'getrandbits' of '_random.Random' objects}
    20000    0.006    0.000    0.006    0.000 {method 'iteritems' of 'dict' objects}
    10000    2.186    0.000    2.186    0.000 {method 'write' of 'file' objects}
    20000    0.005    0.000    0.005    0.000 {setattr}
    10000    0.004    0.000    0.004    0.000 {thread.allocate_lock}
    10000    0.002    0.000    0.002    0.000 {thread.get_ident}
    20002    0.004    0.000    0.004    0.000 {time.time}
```
If I change the code in `report_span` (`reporter.py`) to add the span to the queue from the current thread, rather than adding a callback, the time to execute drops to about 0.3s. I don't think this is a good solution based on the comment there which claims it's not safe (although spans showed up in the UI with no issues).

This was a pretty rough investigation, but I am curious if any performance tests have been done on the python client.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Come up with reasonable performance requirements, and make sure the library is meeting them.

**Comment by yurishkuro** [comment]
A couple thoughts about this. 

First, personally I see little reason to optimize tornado interaction, instead we should get rid of tornado dependency in the reporter in the first place (#31). 

Second, about this:

> method that just makes 10,000 spans in a loop. This function takes about 1.7 seconds to execute.

Microbenchmarks don't tell anything. It's unlikely you'd build a service in Python where a single instance is going to do 10k QPS. Maybe you can squeeze a 100 QPS - the overhead just dropped to 0.017s, less than 2%, which is quite normal for tracing. Add sampling to that, which in reality is rarely more than 1%, and overhead becomes so small it's not worth mentioning. Even if you add more spans, typically those are only added for outbound RPC calls, so you shouldn't compare micro-benchmark with those.

You are correct that the library have not gone through extensive optimization, reasons above are why it hasn't. I did some benchmarks in the original version (tests/test_tracer_benchmark.py). There's always room to optimize something, but pick your battles.

**Comment by nziebart** [comment]
Fair points. I agree that microbenchmarks are not always useful. But to add more context - I initially noticed this because I found that tracing added a significant amount of latency (nearly double) for a certain endpoint that produced a lot of spans (only when the request was traced, of course). A single request might generate many spans; it does not need to be 10,000 QPS - it might only be 100 QPS with 100 spans per request. 

Sampling renders this less of an issue. But, it still affects end users of sampled requests, and consumes CPU time which will affect other requests. In reality the overhead is more than what this test shows because I am not adding any tags or logs.

If there's an easy win like using a different queue impl (one that is threadsafe and doesn't require scheduling a callback to append to it), I think it's worthwhile. Most popular logging and metrics libraries are heavily optimized to minimize overhead - maybe jaeger doesn't need to be *heavily* optimized but I think it's fair to expect that tracing a request won't result in significant extra latency.
