### ISSUE TITLE
Support Span References

### ISSUE THREAD

**Issue by nziebart** [jaegertracing/jaeger-client-python#190]
## Requirement - what kind of business use case are you trying to solve?

We are currently working on tracing a distributed system that uses message queues between services to process events. Some steps involve batch processing. e.g. - 1,000 events will be taken out of a queue, all processed together, and inserted into downstream queues.

## Problem - what in Jaeger blocks you from solving the requirement?

The problem we're running into is how to model these batch operations. Each event has a trace associated with it, and ideally these batch operations would show up in traces for all events that were in the batch. Conceptually, what I'd like to do is create one span for the batch processing (and perhaps some child spans within it) - and associate it as a child of all the traces of events in the batch.

It seems like the opentracing API might support this type of use case via references. However the Python library doesn't currently support them - instead it just picks the first reference and uses it as the parent.

I am curious if jaeger backend supports using references in this way. If I were to create a span with multiple references, would it show up in all of those traces in the UI? Further - is there any practical difference between using `CHILD_OF` and `FOLLOWS_FROM`?

I understand that the span would need to pick one of them to use for its trace id, but I am not too concerned about that for now.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

If this is already supported in the backend - maybe as simple as including the reference information in the thrift messages?

**Comment by yurishkuro** [comment]
The backend supports storing arbitrary number of span references. Most Jaeger clients support then. Looks like Python client has a gap there, we should fix it.

Supporting multiple references in the UI is a different story. We haven't worked out how visualizations would work in that case. Suggestions or PRs are welcome. At minimum the span details can list all references as hyperlinks to other traces.

**Comment by nziebart** [comment]
I think having the span references as tags/links would be a good start. Another part that would be useful is: when showing a trace, also show any spans that reference spans in that trace.

I'm not sure exactly how this second part would be implemented in the query layer. When retrieving a given trace, we'd need to find any spans that reference that trace, plus all of their descendants. I assume that one of the spans in the set of parent references would have to be chosen as the "primary", from which we'd assign the trace id. So, maybe (1) find all spans with references to the trace, that aren't already part of the trace (i.e., that don't have the same trace id) (2) get the trace ids for those spans, (3) fetch those traces, (4) post filter for spans that are descendants of the referencing spans.

This assumes we have a way to perform query (1) above.

It almost seems like it'd be easier to create a new trace id if you have multiple parents. In this way it could be modeled as a sub-trace that belongs to multiple other traces, defined via references. This would eliminate the need to post-filter, and would get rid of the arbitrary selection of a primary span. (Also what if the "primary" span is not sampled but some other parent is? - in this solution we'd sample the new trace if any parent is samped)

There's also a question of whether other parent references of those spans should be included in the view - but for the use case I'm describing here, that wouldn't be necessary/useful. I'd rather click a link to view traces for events in the same batch.

**Comment by nziebart** [comment]
FWIW - we're prototyping a workaround solution for this use case. Essentially, for "batch" operations, we create a separate span for every trace in the batch. Each of those spans is identical, and is the child of exactly one trace from the batch. If sub-operations are performed within the batch operation, we create duplicate spans for those in the same manner.

This gets us what I'm describing above in the UI - but is not great for efficiency as there is a lot of duplication of data.

**Comment by bhavin192** [comment]
I'm working on adding support for references
