### ISSUE TITLE
Eventlet and jaeger_client

### ISSUE THREAD

**Issue by roopakparikh** [jaegertracing/jaeger-client-python#191]
## Requirement - what kind of business use case are you trying to solve?
Making Jaeger work with OpenStack services.
OpenStack services use eventlet. Jaeger client uses tornado thread/ioloop which don't play well with eventlet.

## Problem - what in Jaeger blocks you from solving the requirement?
Jager client tracer creation creates Tornado based Repoter (should be renamed IMHO to TornadoReporter) by default, make it configurable and let caller add its own.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Looking at the code, it looks like the 'Reporter' is pretty dependent on Tornado and ioloop.
The best way to address this problem is to 

a) Remove that dependency and rename/move the Reporter to a TornadoReporter library (either in the same package or better in a separate python package).
b) Let caller specify their own Reporters.

**Comment by yurishkuro** [comment]
My preference is to do this: https://github.com/jaegertracing/jaeger-client-python/issues/31#issuecomment-336728569

**Comment by roopakparikh** [comment]
@yurishkuro The problem is more widespread, see local_agent_net.py, sampler.py both of them assume tornado ioloop to be present and working. How will the mentioned proposal solve the problem?

**Comment by yurishkuro** [comment]
by removing dependency on Tornado from everywhere in the client.

**Comment by scorpioxiatian** [comment]
Hello. I have a trouble, My service use eventlet, and when i do 'span.finish()' , I can see report in the log, But I can't see this trace in jaeger UI ? How can i do?
