### ISSUE TITLE
initialize_tracer() enters an infinite loop

### ISSUE THREAD

**Issue by ryzokuken** [jaegertracing/jaeger-client-python#198]
## Requirement - what kind of business use case are you trying to solve?

I'm trying to use this module to trace a python flask application

## Problem - what in Jaeger blocks you from solving the requirement?

`config.initialize_tracer()` enters an infinite loop, for some reason.

Config object:

```python
    cfg = Config(
        config={
            'sampler': {'type': 'const', 'param': 1},
            'local_agent': {'reporting_host': host}
        },
        service_name=name
    )
```

I could trace this down to `LocalAgentSender::_create_new_thread_loop`, but no idea why this would fail.

**Comment by black-adder** [comment]
Could you provide the minimal viable code to reproduce? What versions of flask, jaeger-client, tornado, python, etc are you using?

**Comment by ryzokuken** [comment]
@black-adder you could try importing https://pypi.org/project/grtracer/ (https://github.com/ryzokuken/grtracer), and initializing an object of class `GrTracer`, and it would fail.
