### ISSUE TITLE
tornado 5.* support

### ISSUE THREAD

**Issue by andriykohut** [jaegertracing/jaeger-client-python#201]
## Requirement

Support for tornado 5.*

## Problem

A new version of tornado was recently [released](http://www.tornadoweb.org/en/stable/releases/v5.0.0.html), but this package has a restriction on a version.

## Proposal

Allow this package to be used with tornado 5.x, it seems like all current tornado usages should "just work", so hopefully it's as easy as bumping the restriction in `setup.py` 🤞

**Comment by black-adder** [comment]
I think we want to remove the tornado dependency completely instead: https://github.com/jaegertracing/jaeger-client-python/issues/31

May I ask for your use case? tornado is used internally by the client and should have no affect on your service. What would bumping to 5.x get us?

**Comment by andriykohut** [comment]
> May I ask for your use case? tornado is used internally by the client and should have no affect on your service. What would bumping to 5.x get us?

This is mostly useful for developers who use tornado as a web server/client and want to use the tracing or work on another package which has this package as a dependency. This restriction doesn't allow the developers to use the latest version of tornado.

> I think we want to remove the tornado dependency completely instead

Sounds great. But even with optional dependency, there will still be a restriction on tornado version, so it seems like it still makes sense to do this.

**Comment by andriykohut** [comment]
I guess I'm complicating things, I just meant that this restricts a `tornado` version for developers who want to use the latest tornado directly (not merely as a dependency), alongside with `jaeger-client-python`.

**Comment by yurishkuro** [comment]
I think it's ok to relax the restriction, but needs testing, as we have no idea if the code will work with v5

**Comment by yurishkuro** [comment]
Done in #247, released in 4.1.0
