### ISSUE TITLE
5.0.0 Design

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger-client-python#205]
## Requirement - what kind of business use case are you trying to solve?

The python client was not architected in line with the other clients. For example, adding a new HTTP sender will require an extensive surgery and a lot of technical debt to maintain backwards compatibility; in the other clients, adding a new HTTP sender was a breeze.

There are other tasks we can accomplish such as:

- Reduce the public API to prevent semver issues #185 
- Remove the `enabled` config variable #145
- Remove tornado dependency #235

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Here's a list of changes, I'll try to make this as exhaustive as possible but I may be missing some changes:

- Create a new `Sender` interface ala the [golang client](https://github.com/jaegertracing/jaeger-client-go/blob/master/transport.go) which supports just `append` and `flush` as begun [here](https://github.com/jaegertracing/jaeger-client-python/blob/fbefb070c6dce91e757fecebbe8add760fe5d620/jaeger_client/senders.py). `LocalAgentSender` should be removed entirely and assimilated into `UDPSender` (or made a private class). `Reporter` should accept a `Sender` instead of `LocalAgentSender`.
- `LocalAgentHTTP(host, sampling_port, throttling_port)` -> `RemoteConfigManager(host, config_port)`. Since sampling_port and throttling_port is always the same, we can unify them. Update `RemoteThrottler` and `RemoteControlledSampler` to accept `RemoteConfigManager` instead of `LocalAgentSender`.
-  `config.py` changes
   - Update `throttler`
      - Remove `port`
   - Remove `sampling_refresh_interval`
   - Update `sampler`
      - Add `refresh_interval`
   - Remove `enabled` #145
   - Add `remote_config`
      - Add `host`
      - Add `port`
   - Remove `reporter_batch_size`
   - Remove `reporter_flush_interval`
   - Remove `logging`
   - Rename `local_agent` -> `reporter`
      - Remove `enabled`
      - Rename `reporting_host` -> `host`
      - Remove `reporting_port` -> `port`
      - Add `batch_size`
      - Add `flush_interval`
      - Add `log_spans`
 - Remove all deprecated functions such as `span.error` and `span.info`
 - Reduce the scope of the API and make private certain fields. Fields TBD.
 - Remove tornado dependency.

I'll keep adding to this list, probably missing something.

## Any open questions to address

- Internally, the bare minimum config we use to enable tracing is `enabled: true`, not sure what the impact of removing will be.
- I've checked internally and these breaking changes should have 0 impact on our customers, cannot say the same for external users.

**Comment by yurishkuro** [comment]
is major rev the only way forward?

**Comment by black-adder** [comment]
I'll take a look, but I suspect the code we get out of it will not be the cleanest.

**Comment by xmm1989218** [comment]
when will 4.0.0 release?

**Comment by Lawouach** [comment]
Hello, just a friendly ping to say I'm also excited to get my hands on that next release (specially to get an implementation of ̀start_active_span` from opentracing 2)

Good job all around folks! :)
