### ISSUE TITLE
 Does jaeger python client support python3.5 now?  

### ISSUE THREAD

**Issue by zhengyifan** [jaegertracing/jaeger-client-python#225]
From CONTRIBUTING.md, we know that jaeger client only supports Python 2.7, but we try to use it in python 3.5 and it works fine。
So whether it supports python3.5 or not?

**Comment by black-adder** [comment]
Yes, python 3 is supported https://github.com/jaegertracing/jaeger-client-python/blob/79d968f65d6fd58a4a56ebeae9ab4a6a908a6809/CHANGELOG.rst#390-2018-04-20. Sorry we forgot to update our documentation
