### ISSUE TITLE
Support for 128 bit trace_id

### ISSUE THREAD

**Issue by bhavin192** [jaegertracing/jaeger-client-python#228]
## Requirement - what kind of business use case are you trying to solve?
I'm trying to implement Jaeger tracing in a flask app which will be running on [Fission](https://fission.io/) 

## Problem - what in Jaeger blocks you from solving the requirement?
The Jaeger Python client currently does not support 128bit tracing id while some of the other clients do support it.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
If the support of 128 bit trace_id is planned for Python client I would like to make the change and send PR for it.

**Comment by black-adder** [comment]
Yes, we definitely want to support 128 bit trace_ids and would really appreciate it if you can put up a PR for it.

**Comment by bhavin192** [comment]
@black-adder thanks, I have started working on this.
