### ISSUE TITLE
Clean-up pins in the dependencies

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-python#232]
We are pinning too many test dependencies, those pins are starting to create cascading issues between them. We need to try to remove most of the pins, and find alternative solutions for cases like this:
```
            # pinned to avoid RemovedInPytest4Warning
            'pytest>=3.7.0,<3.8.0',
```

**Comment by bhavin192** [comment]
While going through setup.py I found that we are using `pytest-tornado` which seems to be not maintained any more. https://github.com/eugeniy/pytest-tornado/issues/41 https://github.com/eugeniy/pytest-tornado/issues/37
We are pinning the pytest version to avoid the warnings created by `pytest-tornado`
