### ISSUE TITLE
why  hasn't  HTTPHeadersCarrier

### ISSUE THREAD

**Issue by zhanglianquan** [jaegertracing/jaeger-client-python#238]
impoort opentracing
opentracing.HTTPHeadersCarrier

 AttributeError: module 'opentracing' has no attribute 'HTTPHeadersCarrier'

**Comment by zhanglianquan** [comment]
other language ,  why has  HTTPHeadersCarrier from  opentracing? such
![image](https://user-images.githubusercontent.com/20316829/52925102-90c6ac00-336a-11e9-87b0-fe6f195af3d0.png)

**Comment by yurishkuro** [comment]
Go has only one common way of representing HTTP headers, so including a helper in the opentracing library made sense. In Python there's no such standard. 

This is a question for opentracing-python, not Jaeger.
