### ISSUE TITLE
use official website‘s issue

### ISSUE THREAD

**Issue by zhanglianquan** [jaegertracing/jaeger-client-python#239]
with tracer.start_span('TestSpan') as span:
        span.log_kv({'event': 'test message', 'life': 42})

        with tracer.start_span('ChildSpan', child_of=span) as child_span:
            span.log_kv({'event': 'down below'})

time.sleep(2)   # yield to IOLoop to flush the spans - https://github.com/jaegertracing/jaeger- 
client-python/issues/50
 tracer.close()  # flush any buffered spans

issue： 

![image](https://user-images.githubusercontent.com/20316829/52927090-b99f6f00-3373-11e9-8a34-c9ff8f959974.png)

**Comment by zhanglianquan** [comment]
use use official website‘s demo  issue？
the content is same about the ChildSpan and it's parent TestSpan , only span's operation_name is diffrence , why can't show  unique operation_name TestSpan  in jaeger ui

**Comment by yurishkuro** [comment]
When you create a span, you create a span. If it's operation name is different then it will show in the UI. This is by design.

Maybe what you want is to only see the entry spans (aka endpoint names) in the dropdown, and not the inner spans within a service. It's possible but will require a sizeable change in the Jaeger backend.

**Comment by zhanglianquan** [comment]
> When you create a span, you create a span. If it's operation name is different then it will show in the UI. This is by design.
> 
> Maybe what you want is to only see the entry spans (aka endpoint names) in the dropdown, and not the inner spans within a service. It's possible but will require a sizeable change in the Jaeger backend.

we need  show same operation name  in the dropdown

**Comment by zhanglianquan** [comment]
> When you create a span, you create a span. If it's operation name is different then it will show in the UI. This is by design.
> 
> Maybe what you want is to only see the entry spans (aka endpoint names) in the dropdown, and not the inner spans within a service. It's possible but will require a sizeable change in the Jaeger backend.

we need  show same operation name  in the dropdown

**Comment by zhanglianquan** [comment]
i want is that to only see the entry spans (aka endpoint names) in the dropdown,

**Comment by zhanglianquan** [comment]
> When you create a span, you create a span. If it's operation name is different then it will show in the UI. This is by design.
> 
> Maybe what you want is to only see the entry spans (aka endpoint names) in the dropdown, and not the inner spans within a service. It's possible but will require a sizeable change in the Jaeger backend.

i want is that to only see the entry spans (aka endpoint names) in the dropdown,

**Comment by black-adder** [comment]
Can you create a ticket in the main jaeger [repo](https://github.com/jaegertracing/jaeger)? It looks like you only want to see root spans (aka endpoint names) in the list and this will require a large amount of changes in the backend.

**Comment by zhanglianquan** [comment]
> Can you create a ticket in the main jaeger [repo](https://github.com/jaegertracing/jaeger)? It looks like you only want to see root spans (aka endpoint names) in the list and this will require a large amount of changes in the backend.

other jaeger client  such as  :
![image](https://user-images.githubusercontent.com/20316829/53215838-62f4a680-368d-11e9-8b21-b246d0929b0f.png)

 TestSpan is only showing in jaeger ui dropdown , because 
TestSpan and ChildSpan are the same content， why not show one?
