### ISSUE TITLE
jaeger-client-python‘s bug in jager ui dropdown widget

### ISSUE THREAD

**Issue by HadesJim** [jaegertracing/jaeger-client-python#243]
When we deployed jaeger-client-python to the production environment, we found a jaeger ui display bug.

**Comment by HadesJim** [comment]
![image](https://user-images.githubusercontent.com/48077924/53539837-1ce88880-3b4e-11e9-80ee-efdb341c0463.png)
![image](https://user-images.githubusercontent.com/48077924/53539866-338edf80-3b4e-11e9-9fe3-534488be6e9f.png)



V2/order/cart/index is a subrequest of /order/cart_info, and the two contents are the same. Why do you display the /order/cart_info request in the jaeger-ui dropdown control?

![image](https://user-images.githubusercontent.com/48077924/53540044-e3644d00-3b4e-11e9-897f-85ba8828e71a.png)




The two contents of v2/order/cart/index and /order/cart_info are the same, why is it the same? V2/order/cart/index is just a /order/cart_info subrequest

![image](https://user-images.githubusercontent.com/48077924/53540125-39d18b80-3b4f-11e9-95dd-e3e435f43cdf.png)
![image](https://user-images.githubusercontent.com/48077924/53540141-48b83e00-3b4f-11e9-9e96-5943ad3802f1.png)

**Comment by HadesJim** [comment]
Then I use the official website example is the same bug，

**Comment by yurishkuro** [comment]
I don't understand what you see as a bug here. The search returns any traces that match the search criteria. The trace contains both `/order/cart_info` and `v2/order/cart/index` spans, so it shows in both results.
