### ISSUE TITLE
tracer object has no attribute start_active_span. using python lib

### ISSUE THREAD

**Issue by gane5hvarma** [jaegertracing/jaeger-client-python#244]
As shown in the tutorial https://github.com/yurishkuro/opentracing-tutorial/tree/master/python/lesson02 . 
when i execute wiht tracer.start_span its working. but, using tracer.start_active_span is giving me an error saying tracer object has no attribute start_active_span

**Comment by gane5hvarma** [comment]
@yurishkuro

**Comment by arwineap** [comment]
@gane5hvarma I was having this issue, and noticed that I had opentracing version 1.3, but start_active_span was added in 2.0.0

https://github.com/opentracing/opentracing-python/commit/2f79bf319fb727da9ef451b4107179eb59e90eb8#diff-a1898244c8c6ea29725a1d5333973b9aR62

**Comment by arwineap** [comment]
These actually seem to be the core of my issue after downgrading to 0.2.0

https://github.com/opentracing-contrib/python-flask/issues/29

https://github.com/jaegertracing/jaeger-client-python/issues/199

**Comment by yurishkuro** [comment]
Duplicate of #199
