### ISSUE TITLE
Support flushing span queue at process exit

### ISSUE THREAD

**Issue by nziebart** [jaegertracing/jaeger-client-python#246]
## Requirement - what kind of business use case are you trying to solve?

We would like to ensure all tracing data is flushed to the backend before exiting the Python process. We have many jobs that are short-lived python processes, and the entire process is traced. Since the very last call to `span.finish()` happens right before the process exits, that span does not make it to the backend, because it is still in the in-memory span queue.

## Problem - what in Jaeger blocks you from solving the requirement?

There is no supported way to flush the in-memory queue, or wait until it is flushed.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Add a `tracer.flush()` method that will ensure all currently enqueued spans are sent to the backend before returning.

Probably the simplest solution is to call `Reporter._submit` synchronously on the entire queue. Alternatively we could wait until the length of the queue is zero, but that does not necessarily mean that the background thread has finished sending all the data.

We currently implement this in some apps by simply calling `time.sleep(3)`

## Any open questions to address

An edge case here could be if some background threads continue to submit spans while the `flush` method is being called. I think we could make the contract of this function that it will only flush spans that have been enqueued prior to the invocation of the method.

We may also want to provide a timeout, in case the function blocks when trying to acquire the flush lock (implementation could be acquiring the lock with the timeout).

**Comment by presize-florian** [comment]
Any updates on this?

**Comment by vlad-ivanov-name** [comment]
For anyone stumbling upon this in 2021, opentelemetry library doesn't seem to have this problem. I was able to reproduce this example with no issues: https://opentelemetry-python.readthedocs.io/en/latest/getting-started.html#configure-exporters-to-emit-spans-elsewhere
