### ISSUE TITLE
Add a MAINTAINERS/CODEOWNERS file

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-python#248]
See jaegertracing/jaeger#254

**Comment by VictoryWekwa** [comment]
Hello, I am an outreachy applicant for this cohort. Please can I work on this issue if it is still open?

**Comment by jpkrohling** [comment]
It's yours!

**Comment by VictoryWekwa** [comment]
Hi @jpkrohling @yurishkuro @pavolloffay @tiffon @joe-elliott @black-adder @objectiser @vprithvi Please would you want to be included in the maintainer's file for this repository?

**Comment by objectiser** [comment]
@VictoryWekwa no

**Comment by jpkrohling** [comment]
No from me as well.

**Comment by yurishkuro** [comment]
What are we trying to communicate through this file?

**Comment by VictoryWekwa** [comment]
> What are we trying to communicate through this file?

Hello, To list maintainers/codeowners, so I  am trying to get the list of codeowners that will be available. After which I can update the PR.

**Comment by jpkrohling** [comment]
I think we can tackle this in a different manner: given that the list of maintainers from this repository is the same as quite a few other repositories, it would probably be better to create a .github repository, like what the OpenTelemetry folks did. In this repo, we can add a MAINTAINERS.

I don't think it makes sense for codeowners, though.

**Comment by yurishkuro** [comment]
What would MAINTAINERS file signify? Basically, I think we need to be careful with having realistic expectations.

**Comment by jpkrohling** [comment]
The list of maintainers for a repository isn't public, from what I know. Besides, having a maintainers file brings clarity to the community about who is an effective maintainer in which repositories. This repo here is an example: I don't really feel qualified to merge PRs here, even though I have the powers to.

**Comment by yurishkuro** [comment]
@VictoryWekwa please list me as the only maintainer for now.

**Comment by yurishkuro** [comment]
@jpkrohling then .github/MAINTAINERS doesn't make much sense, since it will indicate a larger group responsible for ALL Jaeger repos, which is not the case.

**Comment by jpkrohling** [comment]
The .github/MAINTAINERS would only contain the "at jaegertracing/jaeger-maintainers" group, which is the only set of maintainers/admins for quite a few repositories. I think we might have extra people on a few repositories, so, we can override those first.

**Comment by VictoryWekwa** [comment]
> @VictoryWekwa please list me as the only maintainer for now.

Alright. Will do.
