### ISSUE TITLE
Bug: span.finish() reports duplicate spans

### ISSUE THREAD

**Issue by jan25** [jaegertracing/jaeger-client-python#251]
Current `span.finish()` [implementation](https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/span.py#L60) just keeps tracks of `end_time`, and reports span on each call which will result in duplicate spans under same trace.

Expected behavior would be- only report the span the first `finish()` is called and fail from second time onwards. Maybe we just need a simple check if the `end_time` was in the past?

This can be reproduced with const sampler, other kind of sampler might skip reporting duplicate spans

**Comment by yurishkuro** [comment]
OpenTracing leaves tracer behavior as undefined if span.finish() is called >1 times, so technically this is not a bug. Yes, we may want to put a guard and log an error message if that happens. But you should really look into your instrumentation and fix it to not call finish twice.

**Comment by jan25** [comment]
Thanks! Yes, my instrumentation was buggy. The code didn't actually call `span.finish()` twice, but one of calls was indirect because i did `scope.close()`. I might've missed this spec for [scope_manager](https://github.com/opentracing/opentracing-python/blob/master/opentracing/scope_manager.py#L42).

If having a guard in `span.finish()` is not very useful we can close this issue.

**Comment by yurishkuro** [comment]
I think having a guard is useful, we have it in some other Jaeger clients.

**Comment by condorcet** [comment]
Hm, I found that `span.finish` behavior is inconsistent now. If span isn't sampled it won't be finished in term of flags `finished` and `end_time` https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/span.py#L74 I don't think it's a big problem but it may be uncomfortable  when debugging or for third-party tracing library, for example. cc @jan25

**Comment by jan25** [comment]
Hi @condorcet ! Semantically this behavior of not finishing isn't changed from before this issue/PR. And, span isn't sampled means the respective trace(all spans under it) won't be reported, so marking span as finished or trying to report would be redundant anyway.

Could you explain more on what you're trying to achieve/debug w.r.t non sampled spans?
