### ISSUE TITLE
Thrift error "Expected version 01 but got 02"

### ISSUE THREAD

**Issue by pradeepdogga** [jaegertracing/jaeger-client-python#254]
Hi,

Using the lesson 01 solution in https://github.com/yurishkuro/opentracing-tutorial/tree/master/python/lesson01 I am running into an issue when I am running the same program on ubuntu 14.04 while I have no issue when I run the program on ubuntu 16.04.

The following is the error that I observe in jaeger backend logs:
{"level":"error","ts":1563932465.957273,"caller":"processors/thrift_processor.go:118","msg":"Processor failed","error":"Expected version 01 but got 02","stacktrace":"github.com/jaegertracing/jaeger/cmd/agent/app/processors.(*ThriftProcessor).processBuffer\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:118\ngithub.com/jaegertracing/jaeger/cmd/agent/app/processors.NewThriftProcessor.func2\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/agent/app/processors/thrift_processor.go:82"}

To reproduce:
---------------
Run jaeger on ubuntu 16.04
Run lesson 01 from tutorial on same machine, it works and I can see traces on UI
Run lesson 01 from tutorial on ubuntu 14.04, it gives the above error in jaeger and I cannot see traces on UI.

Any help is appreciated.

Thanks,
Pradeep.

**Comment by pradeepdogga** [comment]
Update: This was because TCompactProtocol.py in the python 2.7 packages in 14.04 had version set to 2.

**Comment by yurishkuro** [comment]
not sure I understand how that's possible. Isn't that a property of the Python library, not the OS version?

**Comment by pradeepdogga** [comment]
Exactly. I didn't understand it either.
