### ISSUE TITLE
Problem with Jaeger Tracing with flask

### ISSUE THREAD

**Issue by hitesh1907nayyar** [jaegertracing/jaeger-client-python#263]
Hi, 

I am using the below python file to get a trace of the request in jaeger. 

from flask import Flask
from flask import request
import requests
from opentracing_instrumentation.client_hooks import install_all_patches
from jaeger_client import Config
from flask_opentracing import FlaskTracer

@app.route('/')
def pull_requests():

  github_url = "https://api.github.com/repos/opentracing/opentracing-python/pulls"
  #print(github_url)
  r = requests.get(github_url)

  json = r.json()
  pull_request_titles = map(lambda item: item['title'], json)

  return 'OpenTracing Pull Requests: ' + ', '.join(pull_request_titles)

def initialize_tracer():
  config = Config(
      config={
          'sampler': {'type': 'const', 'param': 1}
      },
      service_name='hello-world')
  print("hitesh")
  return config.initialize_tracer() # also sets opentracing.tracer

app = Flask(__name__)
tracer = FlaskTracer(initialize_tracer, trace_all_requests=True, app=app)
install_all_patches()

if __name__ == '__main__':
    app.run(debug=True,host='0.0.0.0', port=5000)
#flask_tracer = FlaskTracer(initialize_tracer, True, app)

I am getting below error continously. 

106.212.171.140 - - [21/Oct/2019 17:30:16] "GET / HTTP/1.1" 500 -
INFO:werkzeug:106.212.171.140 - - [21/Oct/2019 17:30:16] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1947, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2241, in preprocess_request
    rv = func()
  File "/usr/local/lib/python2.7/site-packages/flask_opentracing/tracing.py", line 39, in start_trace
    self._before_request_fn(traced_attributes)
  File "/usr/local/lib/python2.7/site-packages/flask_opentracing/tracing.py", line 118, in _before_request_fn
    span_ctx = self.tracer.extract(opentracing.Format.HTTP_HEADERS,
  File "/usr/local/lib/python2.7/site-packages/flask_opentracing/tracing.py", line 62, in tracer
    self.__tracer = self.__tracer_getter()
  File "/home/ec2-user/pythonwithsmalltrace.py", line 15, in initialize_tracer
    return config.initialize_tracer() # also sets opentracing.tracer
  File "/usr/local/lib/python2.7/site-packages/jaeger_client/config.py", line 365, in initialize_tracer
    self._initialize_global_tracer(tracer=tracer)
  File "/usr/local/lib/python2.7/site-packages/jaeger_client/config.py", line 434, in _initialize_global_tracer
    opentracing.set_global_tracer(tracer)
AttributeError: 'module' object has no attribute 'set_global_tracer'
106.212.171.140 - - [21/Oct/2019 17:30:17] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
INFO:werkzeug:106.212.171.140 - - [21/Oct/2019 17:30:17] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
106.212.171.140 - - [21/Oct/2019 17:30:17] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:106.212.171.140 - - [21/Oct/2019 17:30:17] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
106.212.171.140 - - [21/Oct/2019 17:30:17] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:106.212.171.140 - - [21/Oct/2019 17:30:17] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
106.212.171.140 - - [21/Oct/2019 17:30:18] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
INFO:werkzeug:106.212.171.140 - - [21/Oct/2019 17:30:18] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
106.212.171.140 - - [21/Oct/2019 17:30:19] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:106.212.171.140 - - [21/Oct/2019 17:30:19] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
106.212.171.140 - - [21/Oct/2019 17:30:20] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:106.212.171.140 - - [21/Oct/2019 17:30:20] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

Can somebody please help me as where is the problem.

**Comment by yurishkuro** [comment]
set_global_tracer did not exist in the earlier versions of opentracing-python, make sure you're using consistent dependnecies.

**Comment by hitesh1907nayyar** [comment]
Hi @yurishkuro 

Thanks for the reply. I am using below dependencies. Can you please help provide the direction as what should i do. 


[ec2-user@ip-172-31-17-90 ~]$ sudo pip install flask_opentracing
Requirement already satisfied: flask_opentracing in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: Flask in /usr/local/lib/python2.7/site-packages (from flask_opentracing)
Requirement already satisfied: opentracing<2.1,>=2.0 in /usr/local/lib/python2.7/site-packages (from flask_opentracing)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python2.7/site-packages (from Flask->flask_opentracing)
Requirement already satisfied: click>=5.1 in /usr/local/lib64/python2.7/site-packages (from Flask->flask_opentracing)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python2.7/site-packages (from Flask->flask_opentracing)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python2.7/site-packages (from Flask->flask_opentracing)
Requirement already satisfied: futures in /usr/lib/python2.7/dist-packages (from opentracing<2.1,>=2.0->flask_opentracing)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib64/python2.7/site-packages (from Jinja2>=2.10.1->Flask->flask_opentracing)

**Comment by yurishkuro** [comment]
this looks a bit suspicious: `opentracing<2.1,>=2.0`, it should be `>=2, <3`

**Comment by yurishkuro** [comment]
I recommend using pip-compile set of tools to ensure that your project's dependencies are consistent.

**Comment by mohit-chawla** [comment]
@yurishkuro , on a separate note (but related to flask): 
Problem: I have been noticing that spans not reported/flushed unless I call tracer.close() manually inside an API. (which is not a good idea, because i dont want to keep creating a new tracer object for each API request.)

Stack: flask (monkey patched, gevent) --> gevent creates a user-level thread for each request.

Am i missing something? Do i have to manually flush spans for that API request (before the user-level thread is closed?)

Thanks in advance.

**Comment by mohit-chawla** [comment]
Also, @yurishkuro regarding 👆 , ideally the reporter should be  reporting every 1 second, but it does not report: https://github.com/jaegertracing/jaeger-client-python/blob/2bb9d0ca9fc2e0517226b632de0f83866d3984c8/jaeger_client/reporter.py#L79

**Comment by yurishkuro** [comment]
I am not familiar with gevent and its threading model. At Uber, in the past, the Flask-like applications were forking a number of child processes for handing requests, and the forking behavior was conflicting with Jaeger thread until we started doing Jaeger initialization in a `@postfork` function. You might be having a similar issue.

**Comment by mohit-chawla** [comment]
okay, in that case -- 
1. Did you had (and in general we need to) a jaeger initialization for each-child-process? 
2. If yes to (1.), did you close the tracer/reporter object manually to flush the spans before the child process exits? 
Thank you for the prompt reply @yurishkuro 🚀 👍

**Comment by yurishkuro** [comment]
Yes, by using @postfork annotation we were delaying tracer initialization (and its bg thread) until the child process is started. The child processes were long-lived, so calling close() was not important, because they were continually reporting spans (you might lose a few spans if the process was killed, but in the steady state it was fine). The tracer is supposed to be long-lived.

**Comment by mohit-chawla** [comment]
@yurishkuro (and @condorcet) thanks for help, this worked for me: https://github.com/jaegertracing/jaeger-client-python/issues/256#issuecomment-527991054
