### ISSUE TITLE
Jaeger client does'nt report span to agent (still have log "Reporting span ...")

### ISSUE THREAD

**Issue by ndhcoder** [jaegertracing/jaeger-client-python#265]
## Problem - what in Jaeger blocks you from solving the requirement?
I using Python 2.7.5, Jaeger-client 4.1.0,  Jaeger backend all-in-one latest
My program contain 2 service A, B, when i'm trace a request throught A and B I have problems the are:
+ Backend UI only have spans of service A

In the logs, Service A have log of UDP call (I was added on TUDPTransport.py write())   but in service B: still have log "Reporting span ..." and not any log of UDP call. 
How to resolve it ? 

Detail project: I config jaeger on Openstack Rocky project, config with osprofiler

**Comment by ndhcoder** [comment]
Some logs:
Service A:
![image](https://user-images.githubusercontent.com/41509130/68178294-0f797d00-ffbe-11e9-95d8-b738c352f11f.png)


Service B:
![image](https://user-images.githubusercontent.com/41509130/68178258-e9ec7380-ffbd-11e9-8817-3189125f45cd.png)

**Comment by ndhcoder** [comment]
The report_span_from_ioloop never call on Service B

**Comment by ndhcoder** [comment]
_consume_queue also never call on Service B

**Comment by ndhcoder** [comment]
Log file:
Service A: http://codepad.org/HqZseFUx
Service B: http://codepad.org/iMkPg8Ar

**Comment by ndhcoder** [comment]
The _report_span call on both service

**Comment by ndhcoder** [comment]
I saw tracer on Service B when init doesn't have log on _consume_queue method and not have log of sample interval 60s :( but Service A has it.

**Comment by ndhcoder** [comment]
Have anyone ?

**Comment by ndhcoder** [comment]
I saw io loop of Service A is instance of tornado.platform.epoll.EPollIOLoop object 
But Service B is instance of tornado.platfrom.select.SelectIOLoop Object and call back on Reporter when add to this io_loop type nerver be call.

Why they different when all condition of varible on those method are same all ??

**Comment by lamto20132223** [comment]
@ndhcoder I had the same issue when using Jaeger in combination with Osprofiler in both Rocky and Stein.
As far as I know because Jaeger client uses tornado and it doesn't work with eventlet, but even when trying to turn off eventlet in Openstack code it still doesn't work.
Has anyone got this issue and found the solution yet?

**Comment by condorcet** [comment]
@ndhcoder @lamto20132223 Sounds very similar to https://github.com/jaegertracing/jaeger-client-python/issues/256 Have you try to use latest jaeger-client from sources?

**Comment by ndhcoder** [comment]
> @ndhcoder @lamto20132223 Sounds very similar to #256 Have you try to use latest jaeger-client from sources?

Yes. I'm use 4.1.0

**Comment by lamto20132223** [comment]
@condorcet Thanks for your support. I checked #256 and test all your suggest but it not work.
I'm using jaeger-client=4.1.0 and modify follow
 def report_span(self, span):
        self.io_loop.add_callback(self._report_span_from_ioloop, span)
But it doesnt help.
Could you please help me checkout my small source code.
`https://github.com/lamto20132223/github_folder/blob/master/demo.py`

I want to use eventlet.patcher.monkey_patch() but it make jaeger-client fail.

**Comment by condorcet** [comment]
@lamto20132223 I haven't enough time to explore this problem, but yes it's seems that Tornado doesn't work with Eventlet. I've  noticed different implementations of io_loop inside Tornado with/without Eventlet monkey patching.
Also I've seen io_loop hangs on working with `os.fdopen` that patched by Eventlet and this blocks entire loop. Simple tornado coroutines works well (periodic callbacks for example) with Eventlet as I saw.
I'll try to explore the problem deeper.

**Comment by condorcet** [comment]
@lamto20132223 Ah, ok, it's known issue https://github.com/eventlet/eventlet/issues/529 It seems the only possible way is don't do monkey patch of `os`  in eventlet, if it possible in your application.

**Comment by lamto20132223** [comment]
@condorcet I got it, thanks for advice

**Comment by mohit-chawla** [comment]
@condorcet , i am facing similar issue with gevent monkey patched, went through #256 but still it does not work. jaeger==4.1.0
