### ISSUE TITLE
Use service name as label instead of metric name

### ISSUE THREAD

**Issue by alexppg** [jaegertracing/jaeger-client-python#268]
A microservice name called "python_microservice" will create metrics like this:
```
python_microservice_jaeger:finished_spans_created
```
The microservice name it's part of the metric name instead of the label. This is not a prometheus good practice, since it makes it difficult to aggregate metrics from different microservices. The metrics should be:
```
jaeger:finished_spans_created{service_name="python_microservice"}
```
Thanks for your work!

**Comment by yurishkuro** [comment]
I am not seeing where in Jaeger client we would prepend service name like this. Are you sure this is not something you're doing yourself? How do you initialize Jaeger tracer?

**Comment by alexppg** [comment]
The namespace seems to be the part that initializes the name:
```
config = Config(
        config={},
        service_name='your-app-name',
        validate=True,
        metrics_factory=PrometheusMetricsFactory(namespace='your-app-name')
)
```

The `your-app-name` is what I set as `python-microservice`.  If you change the namespace, you can see how the metric name changes.

**Comment by yurishkuro** [comment]
That is how Prometheus client deals with the namespace, not Jaeger. You don't have to pass this namespace, it defaults to blank:

https://github.com/jaegertracing/jaeger-client-python/blob/900c5092b40ca266e29eeeac50b82af1858bfeac/jaeger_client/metrics/prometheus.py#L24

**Comment by alexppg** [comment]
Ah, I see, thanks! But still, a label with the service name would be useful, wouldn't be? Without it, you can't differentiate multiple microservices.

**Comment by yurishkuro** [comment]
Yes, it would make sense as an optional feature. Are you interested in submitting a PR for it?

**Comment by alexppg** [comment]
Sure! I've just opened https://github.com/jaegertracing/jaeger-client-python/pull/269.
