### ISSUE TITLE
Use span.set_baggage_item in Tornado

### ISSUE THREAD

**Issue by sc-syf** [jaegertracing/jaeger-client-python#270]
## Requirement - what kind of business use case are you trying to solve?
`jaeger_client.span.Span.set_baggage_item` need a threading lock, i wonder if it can be used in Tornado.

## Problem - what in Jaeger blocks you from solving the requirement?
the Tornado is a single thread web framework, will it increase the latency of the whole application?

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Should we use the [asyncio.lock](https://docs.python.org/3/library/asyncio-sync.html#lock) ?

I noticed that jaeger_client.span.Span.set_baggage_item used a threading lock:
https://github.com/jaegertracing/jaeger-client-python/blob/v4.0.0/jaeger_client/span.py#L129-L130

But the Tornado web framework provides a single thread application.
Does it hurt the performance of tornado?  How can I avoid it ?

**Comment by yurishkuro** [comment]
> the Tornado is a single thread web framework

That's not correct, we have multi-threaded Tornado apps. Even Jaeger client itself starts a separate thread.

**Comment by sc-syf** [comment]
@yurishkuro yes, I means use this method(`set_baggage_item`) in Tornado application's main thread methods such as `self.finish()` or `self.on_finish()`, does it affect the performance? 
Just as [opentracing-tornado](https://github.com/opentracing-contrib/python-tornado) wrote, it patched the on_finish method and do the span's extract. if  I want to set a baggage in this method, is this a correct way to do that?

**Comment by condorcet** [comment]
> I means use this method(`set_baggage_item`) in Tornado application's main thread methods such as `self.finish()` or `self.on_finish()`, does it affect the performance?
> Just as [opentracing-tornado](https://github.com/opentracing-contrib/python-tornado) wrote, it patched the on_finish method and extracted the span's context. if I want to set a baggage in this method, is this a correct way to do that?

@sc-syf Hi!
As I understood your second question, you can simply override `on_finish` in your application and add `set_baggage_item` before invoking original `on_finish`:
```
def on_finish():
    tracer.active_span.set_baggage_item(...)
    super().on_finish()
```

It's shouldn't affect the performance your application, I don't see the reason why and how it can be.
