### ISSUE TITLE
Need support for JAEGER_AUTH_TOKEN 

### ISSUE THREAD

**Issue by ashwinbasavaraja** [jaegertracing/jaeger-client-python#271]
Looking for authentication between jaeger client collector & agent. As per the documentation, the JAEGER_AUTH_TOKEN defines an optional auth token when reporting over HTTP. But it is only supported in Java - https://dzone.com/articles/protecting-the-collection-of-spans

We need similar support in Python client library.

**Comment by yurishkuro** [comment]
iirc, Python client does not support HTTP reporting in the first place (see #98).
