### ISSUE TITLE
Adding Jaeger client to project causes PyTest to hang while collecting tests

### ISSUE THREAD

**Issue by lukeplausin** [jaegertracing/jaeger-client-python#278]
## Requirement - what kind of business use case are you trying to solve?

Hi there 👋

I am trying to instrument an application with over 1000 unit tests. After a few days of development I was able to get good results in Jaeger using this client library. However I cannot get my change merged in because Jaeger is somehow causing unit tests on the project to fail. PyTest doesn't even start running the suite, it just seems to hang indefintely whilst collecting the tests. I've checked through the debug logs and can't find any obvious cause.

I've noticed that pytest consistently stops at the same number, which is somewhere near 460/1000 tests. Based on the other issues people have had with this library, my guess is that it's some kind of asyncio threading type problem. Perhaps the system runs into some kind of resource limit?

I've tried using a fixture to immediately close tracers after creation (like this test cast):
https://github.com/jaegertracing/jaeger-client-python/blob/2bb9d0ca9fc2e0517226b632de0f83866d3984c8/tests/test_crossdock.py#L49
It hasn't worked though.

## Problem - what in Jaeger blocks you from solving the requirement?

I cannot get my change to include tracing with Jaeger passed in my own project due to unit tests failing to collect in pytest.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I would like to know how other projects are unit tested when using Jaeger. Has anyone else experienced this issue? Any comments, hints or suggestions would be helpful. Thanks!

**Comment by yurishkuro** [comment]
Are you using the default production Jaeger tracer in unit tests? I would not recommend it. You may notice that almost all unit tests in Jaeger client itself instantiate a tracer with in-memory reporter and a const sampler. If you use default production tracer, it creates threads, sends data to UDP, etc. - you don't need any of that in tests.

Another option, whenever I test just the _instrumentation_ (e.g. https://github.com/uber-common/opentracing-python-instrumentation), I tend to avoid concrete tracers altogether and only test with the MockTracer from OpenTracing directly.

**Comment by lukeplausin** [comment]
Thanks for your fast reply!

I wasn't aware that there are different types of tracers, this was not obvious to me from the Jaeger documentation. I noticed from glancing at the source code that the Jaeger client `Config` constructor accepts an `enabled` key, I naively thought that setting this to `True` would disable data collection.

Is there somewhere that I can read about the different types of tracers or configuration options?

Monkey patching with MockTracer objects sounds like a good alternative so I will try this in the meantime and report back.

**Comment by yurishkuro** [comment]
It's not that there are different _types_ of tracers - there's only one Jaeger tracer. But its behavior can vary depending on configuration. If you create it with a simple sampler and in-memory reporter, then the tracer won't be running any background threads, which makes it more suitable for unit tests. But I would still recommend OT MockTracer, because it is officially supported with a read/write API, i.e. you can inspect the spans after collection. The same is possible with Jaeger but you'd likely be relying on internal implementation details. Your aim in the instrumentation is to be independent of the concrete tracer, and only depend on OT.

I admit that configuration options are not exceptionally well documented in the README. Pull requests to improve that are greatly appreciated (in fact, documentation PRs are often more useful than code PRs).

**Comment by lukeplausin** [comment]
@yurishkuro thanks to your help I was able to get the unit tests up and running.

Here is my solution, in case anyone else runs into the same issue:

I was able to run unit tests using the `MockTracer` object from opentracing in place of the real Jaeger client tracers. I decided to re-implement the way that tracing objects are created inside my application. There is now a TraceManager singleton class (class with only one instance), with the methods `get_config` and `get_tracer` to return `Config` and `Tracer` objects respectively. I patched the methods of this singleton object globally inside the `conftest.py` unit test configuration file.

(conftest.py)
`
from opentracing.mocktracer import MockTracer
from my_app.tracing import trace_manager

def get_mock_tracer(self, service_name='my_app'):
    print("CREATING MOCK TRACER {}".format(service_name))
    return MockTracer()

# This function returns a Jaeger "Config" object
trace_manager.get_config = get_mock_tracer
# This function returns a Jaeger "Tracer" object
trace_manager.get_tracer = get_mock_tracer

print("IMPORTED CONFTEST JAEGER")
`

**Comment by lukeplausin** [comment]
I'd like to help if I can, but I'm not very well informed so if I tried to write documentation it wouldn't contain much information. By the way I'm not criticising - I understand the project is a work in progress done on a voluntary basis, and I think you've done a fantastic job with it so far. Thank you for sharing.
