### ISSUE TITLE
create the same trace_id

### ISSUE THREAD

**Issue by oldman1991** [jaegertracing/jaeger-client-python#282]
now， i am use jaeger-client with flask, I start my application with gunicorn my python version is 3.7 . jaeger-client version is 4.3. flask version is 1.1.1 here is my code:
`
       

        request = stack.top.request
        operation_name = request.endpoint
        headers = {}
        for k, v in request.headers:
            headers[k.lower()] = v 
       try:
            span_ctx = self.tracer.extract(opentracing.Format.HTTP_HEADERS,
                                           headers)
            scope = self.tracer.start_active_span(operation_name,
                                                  child_of=span_ctx)
            current_app.logger.info('normal trace_id:{}, span_ctx is None'.format(str(scope.span), span_ctx is None))
            current_app.logger.info('normal headers:{}'.format(str(headers)))
            current_app.logger.info('normal span_ctx is None:{}, id:{}'.format(span_ctx is None, id(span_ctx)))
        except (opentracing.InvalidCarrierException,
                opentracing.SpanContextCorruptedException):
            scope = self.tracer.start_active_span(operation_name)
            current_app.logger.info('error trace_id:{}'.format(str(scope.span)))
            current_app.logger.info('error headers:{}'.format(str(headers)))
`
i find that in a moment ,there is always the same trace_id,like this:
![image](https://user-images.githubusercontent.com/9280199/82990051-27821e00-a02e-11ea-87d3-6c072eb1ab90.png)
the span_ctx is always None, so why the trace_id is always the same? I think there should product different trace_id

**Comment by oldman1991** [comment]
I think I have solved him. In my global trace, there is a span that failed to close properly. When I create a new span, I should specify ignore_active_span to True, and the default is False. It will set your active span to you. The parent of the span
`
    def start_span(self,
                   operation_name=None,
                   child_of=None,
                   references=None,
                   tags=None,
                   start_time=None,
                   ignore_active_span=False,
                   ):
        """
        Start and return a new Span representing a unit of work.

        :param operation_name: name of the operation represented by the new
            span from the perspective of the current service.
        :param child_of: shortcut for 'child_of' reference
        :param references: (optional) either a single Reference object or a
            list of Reference objects that identify one or more parent
            SpanContexts. (See the opentracing.Reference documentation for detail)
        :param tags: optional dictionary of Span Tags. The caller gives up
            ownership of that dictionary, because the Tracer may use it as-is
            to avoid extra data copying.
        :param start_time: an explicit Span start time as a unix timestamp per
            time.time()
        :param ignore_active_span: an explicit flag that ignores the current
            active :class:`Scope` and creates a root :class:`Span`

        :return: Returns an already-started Span instance.
        """
        parent = child_of

        if self.active_span is not None \
                and not ignore_active_span \
                and not parent:
            parent = self.active_span

`

**Comment by gionapaolini** [comment]
@oldman1991 I have the same issue. In my case this only happen after more than 5 concurrent requests to the service. Did you find the cause for your span not closing properly?
