### ISSUE TITLE
How can I disable INFO jaeger loggings, in a tornado integration ?

### ISSUE THREAD

**Issue by ghevge** [jaegertracing/jaeger-client-python#303]
## Requirement - what kind of business use case are you trying to solve?

I would like to know how to stop jaeger from polluting my app logs.

## Problem - what in Jaeger blocks you from solving the requirement?

I have a tornado application in which I use jaeger for tracing. 
jaeger-client==4.3.0
tornado==6.0.4

My problem is that jaeger keeps logging at the INFO level, tons of entries like this :

`INFO [jaeger_tracing:73]: Reporting span ...`

I've tried a bunch of configuration to try to remove these entries, but so far without luck.

My current jaeger logger configurations is:

```
[logger_jaeger]
level = ERROR
qualname = jaeger_tracing
handlers = console
```

## Any open questions to address

How can I stop jaeger from logging all those entries ? 
Thanks

**Comment by yurishkuro** [comment]
"Reporting span" logs are only done when you ask for them via config or by directly wiring logging reporter.

**Comment by ghevge** [comment]
I can disable all the jaeger logging, by setting logging: False in the config. But I don't want that. I just want to disable INFO log entries. (Basically controlling the logging level). And that's the part that I'm not able to figure it out.

**Comment by yurishkuro** [comment]
Logging: false disables logging of spans only

**Comment by ghevge** [comment]
So, in case of errors, I will be safe if I'll set Logging: false in the config  ?

**Comment by ghevge** [comment]
Thanks! Clear now!
