### ISSUE TITLE
ValueError: Unknown sampler type remote

### ISSUE THREAD

**Issue by choeffer** [jaegertracing/jaeger-client-python#320]
**Describe the bug**

As mentioned in https://www.jaegertracing.io/docs/1.18/sampling/ and https://www.jaegertracing.io/docs/1.18/client-features/ it should be possible to use `sampler.type=remote`. But Python fails with an error while initializing the config.

```
2021-08-18 10:52:52,304 Initializing Jaeger Tracer with UDP reporter
2021-08-18 10:52:52,311 Using selector: EpollSelector
Traceback (most recent call last):
  File "/home/choeffer/Dokumente/proj-tvnow/jaeger-test-container/jaeger.py", line 25, in <module>
    tracer = config.initialize_tracer()
  File "/home/choeffer/Dokumente/proj-tvnow/jaeger-test-container/venv/lib64/python3.9/site-packages/jaeger_client/config.py", line 363, in initialize_tracer
    tracer = self.new_tracer(io_loop)
  File "/home/choeffer/Dokumente/proj-tvnow/jaeger-test-container/venv/lib64/python3.9/site-packages/jaeger_client/config.py", line 374, in new_tracer
    sampler = self.sampler
  File "/home/choeffer/Dokumente/proj-tvnow/jaeger-test-container/venv/lib64/python3.9/site-packages/jaeger_client/config.py", line 235, in sampler
    raise ValueError('Unknown sampler type %s' % sampler_type)
ValueError: Unknown sampler type remote
```

**To Reproduce**
1. use the example from https://github.com/jaegertracing/jaeger-client-python#getting-started
2. use 

```
    config = Config(
        config={
            'sampler': {
                'type': 'remote'
            },
            'logging': True,
        },
        service_name='systems.jaeger-test',
        validate=True,
    )
```
3. start Python script

**Expected behavior**

Remote sampling to work and getting the needed info from the jaeger collector.

**Version (please complete the following information):**
 - OS: Fedora 34
 - Jaeger version: 1.18
 - Deployment: locally

**What troubleshooting steps did you try?**

Digged through the code and found that `SAMPLER_TYPE_REMOTE = 'remote'` is defined, see https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/constants.py#L67L68 , but somehow not in the function `sampler` in class `Config`, see https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/config.py#L220L235

**Comment by choeffer** [comment]
# Analysis

1. https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/config.py#L363

   `tracer = self.new_tracer(io_loop)`
 
   creates a new tracer.
   
2. https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/config.py#L368L374

   ```
       def new_tracer(self, io_loop=None):
        """
        Create a new Jaeger Tracer based on the passed `jaeger_client.Config`.
        Does not set `opentracing.tracer` global variable.
        """
        channel = self._create_local_agent_channel(io_loop=io_loop)
        sampler = self.sampler
   ```
   
   calls https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/config.py#L221L235
   
   ```
       def sampler(self):
        sampler_config = self.config.get('sampler', {})
        sampler_type = sampler_config.get('type', None)
        sampler_param = sampler_config.get('param', None)
        if not sampler_type:
            return None
        elif sampler_type == SAMPLER_TYPE_CONST:
            return ConstSampler(decision=get_boolean(sampler_param, False))
        elif sampler_type == SAMPLER_TYPE_PROBABILISTIC:
            return ProbabilisticSampler(rate=float(sampler_param))
        elif sampler_type in [SAMPLER_TYPE_RATE_LIMITING, 'rate_limiting']:
            return RateLimitingSampler(
                max_traces_per_second=float(sampler_param))

        raise ValueError('Unknown sampler type %s' % sampler_type)
   ```
   There, the default value `None` is returned if `type` is empty (default). But this is also the place where the value `remote` throws an error.
   
3. https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/config.py#L375L383

   ```
       if not sampler:
        sampler = RemoteControlledSampler(
            channel=channel,
            service_name=self.service_name,
            logger=logger,
            metrics_factory=self._metrics_factory,
            error_reporter=self.error_reporter,
            sampling_refresh_interval=self.sampling_refresh_interval,
            max_operations=self.max_operations)
   ```

   checks if `sampler` is `None` (default) and returns `sampler=RemoteControlledSampler( ...`. -> use remote controlled sampler.

# Result

So **only** if `type` is empty, the `RemoteControlledSampler` is used. If `type` equals `remote`, the above code throws an error and is unable to handle the input.
From my point of view, it should be possible to set `type` equals `remote` explicitly and not only by leaving out that value.

**Comment by yurishkuro** [comment]
Would you like to submit a fix?

**Comment by choeffer** [comment]
@yurishkuro I will give it a try. I have a rough idea what how to fix it.
