### ISSUE TITLE
Manage specific Sampler with Jaeger Config

### ISSUE THREAD

**Issue by Etienne-Carriere** [jaegertracing/jaeger-client-python#323]
## Requirement - what kind of business use case are you trying to solve?

I would like to use custom Sampler with Jaeger Config (builder)

## Problem - what in Jaeger blocks you from solving the requirement?

Currently in Jaeger Config, it is only possible to set a dict to sampler parameter and so not able to able custom Sampler

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Accept in Jaeger Config a Sampler already configured

**Comment by yurishkuro** [comment]
released in 4.7.0
