### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by alvassin** [jaegertracing/jaeger-client-python#337]
Currently jaeger_client is not flexible enough - [it is not possible](https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/TUDPTransport.py#L31) to specify ipv6 socket.

Could you please add such support? I could do PR by myself, but i am not sure what is the best way to implement it. 

Of course, it would be much more flexible to pass socket object, that could be configured by user. But for current API perhaps it would be better to add one more parameter to the config:

```
config = Config(
    'local_agent': {
        'reporting_host': 'example.com',  # standard option
        'reporting_host_ipv6': 'example.com', # instead?
        'reporting_host_use_ipv6': true,  # one more way?
        'reporting_port': 6831,
    },
    ...
)
```

**Comment by yurishkuro** [comment]
I'd go with `reporting_host_use_ipv6`, unless it can be determined automatically from the look of the address.

**Comment by alvassin** [comment]
@yurishkuro, I've made PR, but perhaps better way is just to use `sock.AF_UNSPEC` [instead of `sock.AF_INET`](https://github.com/jaegertracing/jaeger-client-python/blob/master/jaeger_client/TUDPTransport.py#L31)? 
It should work out-of-the-box, what do you think?

**Comment by alvassin** [comment]
@yurishkuro, thank you very much for your time! Could you please release ipv6 version on pypi?

**Comment by yurishkuro** [comment]
https://pypi.org/project/jaeger-client/4.8.0/

**Comment by alvassin** [comment]
Thank you very much!
