### ISSUE TITLE
Can jaeger-client-python talk to Jaeger collector directly?

### ISSUE THREAD

**Issue by zyxue** [jaegertracing/jaeger-client-python#345]
I am trying to find the equivalent config of `JAEGER_ENDPOINT` as in jaeger-client-java: https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-core#configuration-via-environment, which says

>Setting JAEGER_AGENT_HOST/JAEGER_AGENT_PORT will make the client send traces to the agent via UdpSender. If the JAEGER_ENDPOINT environment variable is also set, the traces are sent to the endpoint, effectively making the JAEGER_AGENT_* vars ineffective.

>When the JAEGER_ENDPOINT is set, the HttpSender is used when submitting traces to a remote endpoint, **usually served by a Jaeger Collector**. If the endpoint is secured, a HTTP Basic Authentication can be performed by setting the related environment vars. Similarly, if the endpoint expects an authentication token, like a JWT, set the JAEGER_AUTH_TOKEN environment variable. If the Basic Authentication environment variables and the Auth Token environment variable are set, Basic Authentication is used.

is this supported in jaeger-client-python?

**Comment by yurishkuro** [comment]
correct.
