### ISSUE TITLE
Should span.tags be a dict?

### ISSUE THREAD

**Issue by dray92** [jaegertracing/jaeger-client-python#70]
Does it make sense for {[span.tags](https://github.com/uber/jaeger-client-python/blob/master/jaeger_client/span.py#L56)} to be a dict object instead of a list? Similar to the implementation in the java client {[source](https://github.com/uber/jaeger-client-java/blob/master/jaeger-core/src/main/java/com/uber/jaeger/Span.java#L60)}

Admittedly, the behavior has been left somewhat ambiguous in [opentracing](https://github.com/opentracing/opentracing-python/blob/master/opentracing/span.py#L116), but shouldn't the Jaeger client libs maintain this degree of parity?

**Comment by yurishkuro** [comment]
Jaeger's internal data model represents tags as a list, so I don't see a compelling reason to change the clients behavior.

**Comment by dray92** [comment]
So, let’s look at this from a consumer’s perspective.

Basic requirement -> if anything goes wrong, set FOO_BAR tag to False, else True; which fits with the expected usage pattern.

In the current world, 
```
currentSpan = ..

try:
    outbound_call_1()
catch SomeException as e:
    currentSpan.set_trag(FOO_BAR, False)
    raise e

try:
    outbound_call_2()
catch SomeOtherException as e:
    currentSpan.set_trag(FOO_BAR, False)
    raise e

currentSpan.set_trag(FOO_BAR, True)
```

Ideally, what I think this should be:

```
currentSpan = ..
currentSpan.set_trag(FOO_BAR, False)
outbound_call_1()
outbound_call_2()
# if you got here, everything must be good
currentSpan.set_trag(FOO_BAR, True)
```

Now, something I am not clear about is, conceptually, how does it make sense to have a level of ambiguity around what span tag will actually be taken into account, when reporting? The only tag values that should be taken into account, are the ones that have been set,on the last invocation of a tag key.

If I call `set_tag` on the same span, for the same tag key, isn’t it intuitive that the last invocation will be the one that is taken into account? Furthermore, when starting a new span from the tracer, the existing logic within tracer stores a dict of tags, not a list {[reference](https://github.com/uber/jaeger-client-python/blob/0392cce88d04fd3f15d6cb6e8a6e7ad053387829/jaeger_client/tracer.py#L82)}.

With the change to dict, most of the existing logic is re-used - if we call the dict `_tags`, then `set_tag(..)` will, by default, write to the dict. When `finish()` is called on the span, the span can be responsible for populating the list of tags, by parsing over the dict; it can then invoke the reporter.

**Comment by yurishkuro** [comment]
It is not difficult as a consumer to make sure you're seeing the tag exactly one. OpenTracing leaves the behavior undefined for a reason, eg. some tracers might send the tags to the backend before the app has a chance to override the value.
