### ISSUE TITLE
no doc for how to set config?

### ISSUE THREAD

**Issue by jiamo** [jaegertracing/jaeger-client-python#72]
I build it and run it fine locally. While mostly the `jaeger server` was in another machine. But I can't find doc to do this.

Through I can infer from this code.
```
    @property
    def local_agent_reporting_port(self):
        # noinspection PyBroadException
        try:
            return int(self.local_agent_group()['reporting_port'])
        except:
            return DEFAULT_REPORTING_PORT

    @property
    def local_agent_reporting_host(self):
        # noinspection PyBroadException
        try:
            return self.local_agent_group()['reporting_host']
        except:
            return DEFAULT_REPORTING_HOST
```
But if there is a doc it will be good for beginning.

**Comment by jiamo** [comment]
I make a misunderstand. I run the docker by the `quick getting start` which I think the agent will be with collection.  After see more document. In production  env the agent may be always with application. (while it may still can split from application I think. May be two application on different machine can use one agent)

**Comment by Weilor** [comment]
@jiamo you're right
And no matter golang jaeger sdk or python jaeger sdk, their doc is not specific. It's disappointed.

**Comment by ror6ax** [comment]
@Weilor - you mean the config format is not clearly defined?

**Comment by Weilor** [comment]
@ror6ax - sorry to reply you so late. What I mean was if someone just read doc he/she can't get all info he/she need,  like how I init a tracer reports to a remote jaeger agent or how I put span context into a http request.

**Comment by yurishkuro** [comment]
@Weilor have you seen https://github.com/yurishkuro/opentracing-tutorial/ ?

**Comment by Weilor** [comment]
@yurishkuro No, and I figured my question by reading code. Although I think it will be helpful if the readme of this repository could contain a brief guidance about how to set config and it is more friendly than looking at another doc for a new user.  And I used golang-jaeger and python-jaeger, and this issue did not get me. So I think this is not big deal.

**Comment by SEJeff** [comment]
@Weilor why not send a PR to include an example or a link to the opentracing-tutorial repo?
