### ISSUE TITLE
Document how to setup dev environment and build client

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-client-python#84]
Once #83 is merged, we need to update the CONTRIBUTING.md to include instructions on how to setup the local development environment and build/test the client, similar to the instructions in [node](https://github.com/jaegertracing/jaeger-client-node/blob/master/CONTRIBUTING.md#developing) and [java](https://github.com/jaegertracing/jaeger-client-java/blob/master/CONTRIBUTING.md#developing) clients.

**Comment by yurishkuro** [comment]
I have those in https://github.com/yurishkuro/opentracing-tutorial/blob/master/python/README.md
