### ISSUE TITLE
Use smaller base image for crossdock image 

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger-client-python#88]
Golang is using scratch so the crossdock image is only 3MB. Do something similar for xdock-py

**Comment by ishanjain28** [comment]
@black-adder I have done a little work on this. I need some help in understanding how to test my image. 

I used alpine as base and my image size currently is 200MB. I can remove packages like gcc py-pip and reduce the size even more. 

Currently, When I try to run my image I get the error `no such file or directory: 'idl/thrift/crossdock/tracetest.thrift'`.

The Dockerfile lives inside crossdock folder and all the commands like `COPY` assume that the docker file is being built from project root. I didn't understand how this was working. So, For my testing purpose I moved `crossdock/Dockerfile` to `{project-root}/Dockerfile`.

**Comment by ishanjain28** [comment]
I forgot to look for the submodule. I cloned the repo recursively and it worked just fine. But I still don't understand why is Dockerfile in `crossdocker/`?

**Comment by ishanjain28** [comment]
The image size has been reduced to 215MB. I tried to remove py-pip after all the deps are installed but that increases size from 215MB to 216MB.

**Comment by black-adder** [comment]
Sorry I need to do a better job at linking issues to PRs. https://github.com/jaegertracing/jaeger-client-python/pull/89 I got to the same size as you. However, I'm kinda incredulous that we can't get it any smaller.

As for why the Dockerfile is inside the crossdock repo is because crossdock is our integration test suite that we use to check compatibility of context propagation between different clients. We bring up docker images of different clients and then test them.

**Comment by ishanjain28** [comment]
@black-adder I have tried a couple of different things like clearing package cache, Removing `gcc` right before starting the program but the image size doesn't changes at all. Since, You've already submitted a PR with same results, I'll take remove mine.

**Comment by yurishkuro** [comment]
We obviously need Python in the final image, but we don't need a lot of intermediate packages and build artifacts which are being included because we run `pip install` inside the final image. One approach would be to run the build/install elsewhere and only copy the final output to a separate image.

But in practice, would it give us much better results? What is the size of the clean Python image itself? And what is the size of the additional compiled packages? If we would only go from 200mb to say 150mb, it's not worth the trouble.

**Comment by yurishkuro** [comment]
The proposed PR did not solve this, and it does not appear to be a particularly pressing issue.
